name: CI

on: pull_request_target

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.number }}/merge
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
      - name: Install dependencies
        run: make dev-env
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: integration
        env:
          V3IO_API: ${{ secrets.V3IO_API }}
          V3IO_ACCESS_KEY: ${{ secrets.V3IO_ACCESS_KEY }}
        run: make integration
